pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "orenharari33/jenkins_push_image"
        DOCKER_TAG = "latest"
        DOCKERHUB_CREDENTIALS = credentials('orenharari33-dockerhub')
    }

    stages {
        stage('Initial Run') {
            steps {
                script {
                    echo "Starting the pipeline..."
                    echo "Docker image: ${DOCKER_IMAGE}:${DOCKER_TAG}"
                    echo "Jenkins is running successfully!"
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline executed successfully!"
        }
    }
}
